POST http://localhost:3001/api/notes  
Content-Type: application/json

{
    "content":"suscribete a midudev  ",
    "important": true,
    "userId":"65ef76b262dce1732d2109f1"
}


###
POST http://localhost:3001/api/notes  
Content-Type: application/json

{ 
}